### ISSUE TITLE
Prolog server page 

### ISSUE THREAD

**Issue by milamhi** [aartikis/RTEC#3]
hi, i'm new with swi prolog ,and i have a school project that requires to built a web expert system . so i heard about prolog server pages and i got a file called webserver.pl . after doing what it's needed of configurations . running my scripts that have the extension *.prolog . i got the following errour .
ERROR: -g run_page: Undefined procedure: psp_session_database/1 ERROR: In: ERROR: [12] psp_session_database(_1102) ERROR: [11] create_session_data('192.168.1.106',_1128) at c:/psp/webserver.pl:651 ERROR: [9] run_page at c:/psp/webserver.pl:81 ERROR: [8] catch(user:run_page,error(existence_error(procedure,...),context(...,_1200)),'$toplevel':true) at c:/program files/swipl/boot/init.pl:386 ERROR: [7] catch_with_backtrace('',error(existence_error(procedure,...),context(...,_1252)),'') at c:/program files/swipl/boot/init.pl:436 ERROR: ERROR: Note: some frames are missing due to last-call optimization. ERROR: Re-run your program in debug mode (:- debug.) to get more detail.
any help ,I'll be thankful

**Comment by aartikis** [comment]
Is this issue related to RTEC?

**Comment by milamhi** [comment]
I'm soory , what you mean ?
