### ISSUE TITLE
initialiseRecognition/3 incompatibility (manual example)

### ISSUE THREAD

**Issue by jacobfriedman** [aartikis/RTEC#7]
`initialiseRecognition(ordered, nodynamicgrounding, nopreprocessing, 1)` in the manual isn't correct.

I peeked at some examples and nodynamicgrounding would need to be removed...  but it was just a quick solution to continue with the simple example.

**Comment by Periklismant** [comment]
Thank you very much for your comment. The manual has been updated.

**Comment by jacobfriedman** [comment]
Thank you very much.
