### ISSUE TITLE
Switch to snake_case over camelCasing

### ISSUE THREAD

**Issue by jacobfriedman** [aartikis/RTEC#8]
Are you open to switch to snake_casing?

I recommend snake since it's a prolog standard - and will be doing so locally with our planned logtalk port (nothing required on your end)

**Comment by Periklismant** [comment]
Sure,  we would prefer to follow the prolog standard. Thank you for this helpful remark.

**Comment by jacobfriedman** [comment]
At first I tried renaming it myself just to help but realised the compilation would throw me for a loop - and that tests would be needed. Thanks for adding the tests module. If you'd like to work together more intimately, I'm free to do so, just let me know what's next on your plate - and if I can help with some abstraction methods.
